export DOTFILES="$HOME/Code/Warsono/dotfiles"
export COMPOSER_GLOBAL_BIN="$HOME/.config/composer/vendor/bin"

# Plugins
plugins=(git nvm node zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete)

# Git shortcuts
alias gs="git s"
alias gl="git l"
alias gll="git ll"
alias gc="git c"
alias gcm="git cm"
alias gpf="git pf"
alias gch="git co"
alias gb="git b"
alias gp="git p"
alias gpl="git pl"
alias gplo="git pl origin"

# Node.js shortcuts
alias n="nvm"
alias p="pnpm"
alias dev="pnpm dev"

# Utils
alias reload="source ~/.zshrc"
alias c="clear"

# Path tambahan
export PATH="$HOME/.local/bin:$DOTFILES/bin:$COMPOSER_GLOBAL_BIN:$PATH"
